<?php

namespace DemoBundle\Repository;

/**
 * AlmacenesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlmacenesRepository extends \Doctrine\ORM\EntityRepository
{
}
